modLoader="javafml"
loaderVersion="[47,)"
license="${mod_license}"

[[mods]]
modId="wrathy_armament"
version="${mod_version}"
displayName="Wrathy Armament"
logoFile=""
authors="SashaKYotoz"
description="${mod_description}"

[[dependencies.wrathy_armament]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
[[dependencies.wrathy_armament]]
modId = "anitexlib"
mandatory = true
versionRange = "[0.4,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.wrathy_armament]]
modId = "playeranimator"
mandatory = true
versionRange = "[1.0.2-rc1+1.20,)"
ordering = "AFTER"
side = "BOTH"




